spring:
  application:
    name: file_upload-download

  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: user
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  data:
    mongodb:
      uri: mongodb://user:user@localhost:27017/
      database: mydb
      gridfs:
        bucket: file_metadata

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 4060