spring:
  application:
    name: demo

  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: user
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/attendance_db
#    username: attendance
#    password: attendance
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: all
      continue-on-error: true
      encoding: UTF-8

server:
  port: 4061